# Generated by Django 3.2.9 on 2021-11-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(max_length=255, primary_key=1, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='123456', max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
