# Generated by Django 3.2.9 on 2021-11-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TakeOutSystem.turnover'),
        ),
    ]
