# Generated by Django 3.2.9 on 2021-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0003_alter_order_r_delivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal_complete_time',
            field=models.DateTimeField(null=True),
        ),
    ]
