# Generated by Django 3.2.9 on 2021-11-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0003_auto_20211108_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cus_id',
            field=models.ForeignKey(default='anony', on_delete=django.db.models.deletion.CASCADE, to='TakeOutSystem.employee'),
        ),
    ]
