# Generated by Django 3.2.9 on 2021-11-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0004_order_cus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cus_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee1', to='TakeOutSystem.employee'),
        ),
    ]
