# Generated by Django 3.2.9 on 2021-11-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0004_alter_order_meal_complete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnover',
            name='turn_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
