# Generated by Django 3.2.9 on 2021-11-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0005_alter_order_cus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='r_delivery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee3', to='TakeOutSystem.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='r_staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee2', to='TakeOutSystem.employee'),
        ),
    ]
