# Generated by Django 3.2.9 on 2021-11-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0006_location_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
